name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INPUT_DIRECTORY: "${{ github.workspace }}/Book_Images"
      OUTPUT_DIRECTORY: "${{ github.workspace }}/Processed_Data/StyleGAN/Processed_Data"
      TFRECORDS_FILE: "${{ github.workspace }}/Processed_Data/StyleGAN/TFRecords/output.tfrecords"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Prepare directories
      run: |
        mkdir -p $INPUT_DIRECTORY
        mkdir -p $OUTPUT_DIRECTORY

    - name: Verify environment variables
      run: |
        echo "INPUT_DIRECTORY: $INPUT_DIRECTORY"
        echo "OUTPUT_DIRECTORY: $OUTPUT_DIRECTORY"
        echo "TFRECORDS_FILE: $TFRECORDS_FILE"

    - name: Run tests
      run: |
        source env/bin/activate
        pytest tests/test_preprocessing.py
        pytest tests/test_create_tfrecords.py
